<a href="https://colab.research.google.com/github/metalearning-inisiatif/Struktur-Superlearning/blob/main/STRUKTUR%20META%20LEARNING/Meta_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

###**Keras vs TensorFlow vs scikit-learn: What are the differences?**

**Tensorflow** is the most famous library in production for deep learning models. Offers automatic differentiation to perform backpropagation smoothly, allowing you to literally build any machine learning model literally. 
**Keras** is a high-level API built on Tensorflow. It is user-friendly and helps quickly build and test a neural network with minimal lines of code. Like building simple or complex neural networks within a few minutes. **Modular** since everything in Keras can be represented as modules. 
**Scikit Learn** is a general machine learning library built on top of NumPy. It features a lot of utilities for general pre and post-processing of data. It is a library in Python used to construct traditional models.




A large part of our product is training and using a machine learning model. As such, we chose one of the best coding languages, Python, for machine learning. This coding language has many packages which help build and integrate ML models. For the main portion of the machine learning, we chose **PyTorch** as it is one of the highest quality ML packages for Python. PyTorch allows for extreme creativity with your models while not being too complex. Also, we chose to include **scikit-learn** as it contains many useful functions and models which can be quickly deployed. Scikit-learn is perfect for testing models, but it does not have as much flexibility as PyTorch. We also include **NumPy** and **Pandas** as these are wonderful Python packages for data manipulation. Also for testing models and depicting data, we have chosen to use **Matplotlib** and** seaborn**, a package which creates very good looking plots. Matplotlib is the standard for displaying data in Python and ML. Whereas, seaborn is a package built on top of Matplotlib which creates very visually pleasing plots.

**SciKit Learn** is a general machine learning library, built on top of NumPy. It features a lot of machine learning algorithms such as support vector machines, random forests, as well as a lot of utilities for general pre- and postprocessing of data. It is not a neural network framework.

**PyTorch** is a deep learning framework, consisting of

     

1.  A vectorized math library similar to NumPy, but with GPU support and a lot of neural network related operations (such as softmax or various kinds of activations)
2.   Autograd - an algorithm which can automatically calculate gradients of your functions, defined in terms of the basic operations
3. Gradient-based optimization routines for large scale optimization, dedicated to neural network optimization
4. Neural-network related utility functions

**Keras** is a higher-level deep learning framework, which abstracts many details away, making code simpler and more concise than in PyTorch or TensorFlow, at the cost of limited hackability. It abstracts away the computation backend, which can be TensorFlow, Theano or CNTK. It does not support a PyTorch backend, but that's not something unfathomable - you can consider it a simplified and streamlined subset of the above.

In short, if you are going with "classic", non-neural algorithms, neither PyTorch nor Keras will be useful for you. If you're doing deep learning, scikit-learn may still be useful for its utility part; aside from it you will need the actual deep learning framework, where you can choose between Keras and PyTorch but you're unlikely to use both at the same time. This is very subjective, but in my view, if you're working on a novel algorithm, you're more likely to go with PyTorch (or TensorFlow or some other lower-level framework) for flexibility. If you're adapting a known and tested algorithm to a new problem setting, you may want to go with Keras for its greater simplicity and lower entry level.

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

#import os
#for dirname, _, filenames in os.walk('/kaggle/input'):
#    for filename in filenames:
#        print(os.path.join(dirname, filename))

from numpy import hstack
from numpy import vstack
from numpy import asarray
from sklearn.datasets import make_blobs
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
 

In [ ]:
# tentang make_blobs
X, y = make_blobs(n_samples=10, centers=3, n_features=2,random_state=1)
print(X.shape)

(10, 2)


In [ ]:

a = np.array((1,2,3))
b = np.array((4,5,6))
print(a)
np.hstack((a,b))

[1 2 3]


array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array((1, 2, 3))
b = np.array((4, 5, 6))
print(a.shape)
np.vstack((a,b))


(3,)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = (1, 2)
b=np.asarray(a)
b

array([1, 2])

In [ ]:
a=list()
b=list()
d=list()
e=list()
a.append(10)
print(a)
a.append(20)
a.append(5)
print("List a berisi: ",a)
c=np.asarray(a)
print("a diubah menjadi array c: ", c)
b.append(-1)
#fungsi extend bersifat iterable dari append yang berulang ulang.
b.extend([1])
b.extend(a)
print("List b adalah: ",b)
c=hstack(b)
print("dengan hstack b diubah dari list menjadi array :",c)
e=d.append(c)
print("Hasil list d mengappend array c: ", e)

[10]
List a berisi:  [10, 20, 5]
a diubah menjadi array c:  [10 20  5]
List b adalah:  [-1, 1, 10, 20, 5]
dengan hstack b diubah dari list menjadi array : [-1  1 10 20  5]
Hasil list d mengappend array c:  None


In [ ]:
print(X)

In [ ]:
print(y)

[2 2 2 1 0 0 0 1 0 1]


In [ ]:
def get_models():
	models = list()
	models.append(LogisticRegression(solver='liblinear'))
	models.append(DecisionTreeClassifier())
	models.append(SVC(gamma='scale', probability=True))
	models.append(GaussianNB())
	models.append(KNeighborsClassifier())
	models.append(AdaBoostClassifier())
	models.append(BaggingClassifier(n_estimators=10))
	models.append(RandomForestClassifier(n_estimators=10))
	models.append(ExtraTreesClassifier(n_estimators=10))
	return models
 

def get_out_of_fold_predictions1(X, y, models):
	meta_X, meta_y = list(), list()
	i=0
	
	#definisikan dulu model kfold yang mau digunakan
	
	kfold = KFold(n_splits=5, shuffle=True)
 
	#_ix di bawah ini menyatakan index
	# dengan settingan kfold ini maka jumlah data akan dibagi menjadi 10 fold, dimana 1 fold berjumlah 120 data
	# Dari 10 fold ini 9 akan dijadikan training dan 1 sisanya akan dijadikan testing. 
	# Jadi train_ix akan berjumlah 9 x 120 record = 1080 record
	# test_ix akan berjumlah 120 record

	for train_ix, test_ix in kfold.split(X):
		i=i+1
		print("nilai i : ",i)
		#print(train_ix,test_ix)
		fold_yhats = list()
		# get data
		train_X, test_X = X[train_ix], X[test_ix]
		train_y, test_y = y[train_ix], y[test_ix]
		print("nilai test_y : ",test_y)
		meta_y.extend(test_y)
		# fit and make predictions with each sub-model
		j=0
		for model in models:
			j=j+1
			print("nilai j : ",j)
			model.fit(train_X, train_y)
			yhat = model.predict_proba(test_X)
			print("yhat  : ",yhat.shape)
			print(yhat)
	 		# Catatan jumlah kolom yhat mengikuti banyaknya kelas dalam dataset. Dalam hal ini 3 
			fold_yhats.append(yhat)
	 
		print("untuk i = ",i," Jumlah baris fold_yhats adalah :", len(fold_yhats)," Jumlah kolom fold_yhats adalah :", len(fold_yhats[0]))
		#print("untuk i = ",i," fold_yhats adalah :", fold_yhats)	
		meta_X.append(hstack(fold_yhats))
	print(meta_X)
	return vstack(meta_X), asarray(meta_y)
 

def fit_base_models(X, y, models):
	for model in models:
		model.fit(X, y)
 
# fit a meta model
def fit_meta_model(X, y):
	model = LogisticRegression(solver='liblinear')
	model.fit(X, y)
	return model
 

def evaluate_models(X, y, models):
	for model in models:
		yhat = model.predict(X)
		acc = accuracy_score(y, yhat)
		print('%s: %.3f' % (model.__class__.__name__, acc*100))
 
#make predictions with stacked model
def super_learner_predictions(X, models, meta_model):
	meta_X = list()
	for model in models:
		yhat = model.predict_proba(X) 
		meta_X.append(yhat)
	meta_X = hstack(meta_X)
	# predict
	return meta_model.predict(meta_X)

In [ ]:
def get_out_of_fold_predictions(X, y, models):
	meta_X, meta_y = list(), list()
	#definisikan dulu model kfold yang mau digunakan
	
	kfold = KFold(n_splits=10, shuffle=True)
 
	#_ix di bawah ini menyatakan index
	# dengan settingan kfold ini maka jumlah data akan dibagi menjadi 10 fold, dimana 1 fold berjumlah 120 data
	# Dari 10 fold ini 9 akan dijadikan training dan 1 sisanya akan dijadikan testing. 
	# Jadi train_ix akan berjumlah 9 x 120 record = 1080 record
	# test_ix akan berjumlah 120 record

	for train_ix, test_ix in kfold.split(X):
		
		fold_yhats = list()
		# get data
		train_X, test_X = X[train_ix], X[test_ix]
		train_y, test_y = y[train_ix], y[test_ix]
		
		meta_y.extend(test_y)
		# fit and make predictions with each sub-model
		#Prediction dari setiap model disimpan sebagai attribut/fitur input dari superlearner model  
		for model in models:
			model.fit(train_X, train_y)
			yhat = model.predict_proba(test_X)
			#print("yhat  : ",yhat.shape)
	 		# Catatan jumlah kolom yhat mengikuti banyaknya kelas dalam dataset. 
			fold_yhats.append(yhat)
		#print("untuk i = ",i," Jumlah baris fold_yhats adalah :", len(fold_yhats)," Jumlah kolom fold_yhats adalah :", len(fold_yhats[0]))
		#print("untuk i = ",i," fold_yhats adalah :", fold_yhats)	
		meta_X.append(hstack(fold_yhats))
	#print(meta_X)
	return vstack(meta_X), asarray(meta_y)
 

In [ ]:
Model=get_models()
print(Model)

[LogisticRegression(solver='liblinear'), DecisionTreeClassifier(), SVC(probability=True), GaussianNB(), KNeighborsClassifier(), AdaBoostClassifier(), BaggingClassifier(), RandomForestClassifier(n_estimators=10), ExtraTreesClassifier(n_estimators=10)]


In [ ]:
Met_X, Met_y = get_out_of_fold_predictions1(X, y, Model)
print(Met_X.shape)
print(Met_y.shape)

In [ ]:
print(Met_X)

In [ ]:
# Membangkitkan dataset klasifikasi dengan dua kelas, 2000 record dan 200 features
X, y = make_blobs(n_samples=2000, centers=2, n_features=200, cluster_std=20,random_state=1)

In [ ]:
# split
X, X_val, y, y_val = train_test_split(X, y, test_size=0.40)
# dengan pembagian ini, 60%  data (1200) dipakai sebagai data training dan sisanya 800 data dipakai sebagai data untuk validasi.
print('Train', X.shape, y.shape, 'Test', X_val.shape, y_val.shape)

Train (1200, 200) (1200,) Test (800, 200) (800,)


In [ ]:
# Inisiasi models dengan get models
models = get_models()

In [ ]:
# Jalankan fungsi get out of fold predictions untuk membangkitkan input bagi superlearner
# Prediksi dari base learner akan menjadi atribut bagi superlearner
# jumlah record untuk superlearner adalah jumlah data test setiap Fold dikalikan dengan jumlah Fold. 
# Jadi jika k=10, dalam setiap Fold, data test berjumlah 120. Diperoleh dari 1200/10. Karena ada 10 fold, maka datatest berjumlah 10*120=1200 baris. 

meta_X, meta_y = get_out_of_fold_predictions(X, y, models)
print('Meta ', meta_X.shape, meta_y.shape)

#print(meta_X)
#Jumlah kolom/atribut hasil adalah sebesar 18.
# 18 berasal dari 9 model memprediksi peluang 2 kelas, yaitu kelas 0 dan 1
# Jumlah baris adalah 10*120=1200. 

Meta  (1200, 18) (1200,)


In [ ]:
# fit base models
# Tahapan ini adalah membandingkan akurasi antara base models dan superlearner model.
fit_base_models(X, y, models)
# fit the meta model
# Metamodel difit menggunakan k-fold prediction yang dihasilkan oleh base learner.
meta_model = fit_meta_model(meta_X, meta_y)

In [ ]:
# evaluate base models
# disini base models dievaluasi keakuratan prediksi kelas.
evaluate_models(X_val, y_val, models)

LogisticRegression: 99.875
DecisionTreeClassifier: 78.250
SVC: 99.875
GaussianNB: 99.875
KNeighborsClassifier: 98.875
AdaBoostClassifier: 95.000
BaggingClassifier: 87.500
RandomForestClassifier: 89.750
ExtraTreesClassifier: 90.875


In [ ]:
# evaluate meta model
# Sebelum meta model melakukan prediksi terhadap X_Val, base models diberi kesempatan dulu untuk melakukan 
# Predict_proba terhadap X_Val. Hasil predict_proba ini menjadi input bagi superlearner.

yhat = super_learner_predictions(X_val, models, meta_model)
print('Akurasi Super Learner: %.3f' % (accuracy_score(y_val, yhat) * 100))

Akurasi Super Learner: 99.875
